name: SwiftLint
on:
  pull_request:
    paths: ["**/*.swift", ".swiftlint.yml"]
  push:
    paths: ["**/*.swift", ".swiftlint.yml"]
jobs:
  lint:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Install SwiftLint
        run: |
          brew update || true
          brew install swiftlint || true
      - name: Run SwiftLint
        run: swiftlint --strict
